//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico.Presentacion.Web.MatriculacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatriculacionEstudianteDto", Namespace="http://schemas.datacontract.org/2004/07/SistemaAcademico.Negocio.Dto")]
    [System.SerializableAttribute()]
    public partial class MatriculacionEstudianteDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PagoRealizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PagoRealizado {
            get {
                return this.PagoRealizadoField;
            }
            set {
                if ((this.PagoRealizadoField.Equals(value) != true)) {
                    this.PagoRealizadoField = value;
                    this.RaisePropertyChanged("PagoRealizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerNombre {
            get {
                return this.PrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerNombreField, value) != true)) {
                    this.PrimerNombreField = value;
                    this.RaisePropertyChanged("PrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoNombre {
            get {
                return this.SegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoNombreField, value) != true)) {
                    this.SegundoNombreField = value;
                    this.RaisePropertyChanged("SegundoNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaOfint", Namespace="http://schemas.datacontract.org/2004/07/SistemaAcademico.Presentacion.Servicios.D" +
        "to")]
    [System.SerializableAttribute()]
    public partial class RespuestaOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaAcademico.Presentacion.Web.MatriculacionService.TipoRespuestaEnum TipoRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Datos {
            get {
                return this.DatosField;
            }
            set {
                if ((this.DatosField.Equals(value) != true)) {
                    this.DatosField = value;
                    this.RaisePropertyChanged("Datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaAcademico.Presentacion.Web.MatriculacionService.TipoRespuestaEnum TipoRespuesta {
            get {
                return this.TipoRespuestaField;
            }
            set {
                if ((this.TipoRespuestaField.Equals(value) != true)) {
                    this.TipoRespuestaField = value;
                    this.RaisePropertyChanged("TipoRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoRespuestaEnum", Namespace="http://schemas.datacontract.org/2004/07/SistemaAcademico.Presentacion.Servicios.D" +
        "to")]
    public enum TipoRespuestaEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERROR = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaOfArrayOfMatriculacionEstudianteRespDto89vZh_Sq3", Namespace="http://schemas.datacontract.org/2004/07/SistemaAcademico.Presentacion.Servicios.D" +
        "to")]
    [System.SerializableAttribute()]
    public partial class RespuestaOfArrayOfMatriculacionEstudianteRespDto89vZh_Sq3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteRespDto[] DatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaAcademico.Presentacion.Web.MatriculacionService.TipoRespuestaEnum TipoRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteRespDto[] Datos {
            get {
                return this.DatosField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosField, value) != true)) {
                    this.DatosField = value;
                    this.RaisePropertyChanged("Datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaAcademico.Presentacion.Web.MatriculacionService.TipoRespuestaEnum TipoRespuesta {
            get {
                return this.TipoRespuestaField;
            }
            set {
                if ((this.TipoRespuestaField.Equals(value) != true)) {
                    this.TipoRespuestaField = value;
                    this.RaisePropertyChanged("TipoRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatriculacionEstudianteRespDto", Namespace="http://schemas.datacontract.org/2004/07/SistemaAcademico.Negocio.Dto")]
    [System.SerializableAttribute()]
    public partial class MatriculacionEstudianteRespDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoEstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaMatriculacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoEstudiante {
            get {
                return this.CodigoEstudianteField;
            }
            set {
                if ((this.CodigoEstudianteField.Equals(value) != true)) {
                    this.CodigoEstudianteField = value;
                    this.RaisePropertyChanged("CodigoEstudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaMatriculacion {
            get {
                return this.FechaMatriculacionField;
            }
            set {
                if ((this.FechaMatriculacionField.Equals(value) != true)) {
                    this.FechaMatriculacionField = value;
                    this.RaisePropertyChanged("FechaMatriculacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3", Namespace="http://schemas.datacontract.org/2004/07/SistemaAcademico.Presentacion.Servicios.D" +
        "to")]
    [System.SerializableAttribute()]
    public partial class RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteRespDto DatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaAcademico.Presentacion.Web.MatriculacionService.TipoRespuestaEnum TipoRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteRespDto Datos {
            get {
                return this.DatosField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosField, value) != true)) {
                    this.DatosField = value;
                    this.RaisePropertyChanged("Datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaAcademico.Presentacion.Web.MatriculacionService.TipoRespuestaEnum TipoRespuesta {
            get {
                return this.TipoRespuestaField;
            }
            set {
                if ((this.TipoRespuestaField.Equals(value) != true)) {
                    this.TipoRespuestaField = value;
                    this.RaisePropertyChanged("TipoRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaOfstring", Namespace="http://schemas.datacontract.org/2004/07/SistemaAcademico.Presentacion.Servicios.D" +
        "to")]
    [System.SerializableAttribute()]
    public partial class RespuestaOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemaAcademico.Presentacion.Web.MatriculacionService.TipoRespuestaEnum TipoRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Datos {
            get {
                return this.DatosField;
            }
            set {
                if ((object.ReferenceEquals(this.DatosField, value) != true)) {
                    this.DatosField = value;
                    this.RaisePropertyChanged("Datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemaAcademico.Presentacion.Web.MatriculacionService.TipoRespuestaEnum TipoRespuesta {
            get {
                return this.TipoRespuestaField;
            }
            set {
                if ((this.TipoRespuestaField.Equals(value) != true)) {
                    this.TipoRespuestaField = value;
                    this.RaisePropertyChanged("TipoRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatriculacionService.IMatriculacionService")]
    public interface IMatriculacionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/RegistrarEstudianteNuevo", ReplyAction="http://tempuri.org/IMatriculacionService/RegistrarEstudianteNuevoResponse")]
        SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfint RegistrarEstudianteNuevo(SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteDto Datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/RegistrarEstudianteNuevo", ReplyAction="http://tempuri.org/IMatriculacionService/RegistrarEstudianteNuevoResponse")]
        System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfint> RegistrarEstudianteNuevoAsync(SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteDto Datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/ConsultarEstudiantesMatriculados", ReplyAction="http://tempuri.org/IMatriculacionService/ConsultarEstudiantesMatriculadosResponse" +
            "")]
        SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfArrayOfMatriculacionEstudianteRespDto89vZh_Sq3 ConsultarEstudiantesMatriculados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/ConsultarEstudiantesMatriculados", ReplyAction="http://tempuri.org/IMatriculacionService/ConsultarEstudiantesMatriculadosResponse" +
            "")]
        System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfArrayOfMatriculacionEstudianteRespDto89vZh_Sq3> ConsultarEstudiantesMatriculadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/ConsultarEstudianteMatriculado", ReplyAction="http://tempuri.org/IMatriculacionService/ConsultarEstudianteMatriculadoResponse")]
        SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3 ConsultarEstudianteMatriculado(int Identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/ConsultarEstudianteMatriculado", ReplyAction="http://tempuri.org/IMatriculacionService/ConsultarEstudianteMatriculadoResponse")]
        System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3> ConsultarEstudianteMatriculadoAsync(int Identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/ModificarEstudianteMatriculado", ReplyAction="http://tempuri.org/IMatriculacionService/ModificarEstudianteMatriculadoResponse")]
        SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3 ModificarEstudianteMatriculado(int Identificacion, SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteDto Datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/ModificarEstudianteMatriculado", ReplyAction="http://tempuri.org/IMatriculacionService/ModificarEstudianteMatriculadoResponse")]
        System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3> ModificarEstudianteMatriculadoAsync(int Identificacion, SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteDto Datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/EliminarEstudianteMatriculado", ReplyAction="http://tempuri.org/IMatriculacionService/EliminarEstudianteMatriculadoResponse")]
        SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfstring EliminarEstudianteMatriculado(int Identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatriculacionService/EliminarEstudianteMatriculado", ReplyAction="http://tempuri.org/IMatriculacionService/EliminarEstudianteMatriculadoResponse")]
        System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfstring> EliminarEstudianteMatriculadoAsync(int Identificacion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatriculacionServiceChannel : SistemaAcademico.Presentacion.Web.MatriculacionService.IMatriculacionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatriculacionServiceClient : System.ServiceModel.ClientBase<SistemaAcademico.Presentacion.Web.MatriculacionService.IMatriculacionService>, SistemaAcademico.Presentacion.Web.MatriculacionService.IMatriculacionService {
        
        public MatriculacionServiceClient() {
        }
        
        public MatriculacionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatriculacionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatriculacionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatriculacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfint RegistrarEstudianteNuevo(SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteDto Datos) {
            return base.Channel.RegistrarEstudianteNuevo(Datos);
        }
        
        public System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfint> RegistrarEstudianteNuevoAsync(SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteDto Datos) {
            return base.Channel.RegistrarEstudianteNuevoAsync(Datos);
        }
        
        public SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfArrayOfMatriculacionEstudianteRespDto89vZh_Sq3 ConsultarEstudiantesMatriculados() {
            return base.Channel.ConsultarEstudiantesMatriculados();
        }
        
        public System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfArrayOfMatriculacionEstudianteRespDto89vZh_Sq3> ConsultarEstudiantesMatriculadosAsync() {
            return base.Channel.ConsultarEstudiantesMatriculadosAsync();
        }
        
        public SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3 ConsultarEstudianteMatriculado(int Identificacion) {
            return base.Channel.ConsultarEstudianteMatriculado(Identificacion);
        }
        
        public System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3> ConsultarEstudianteMatriculadoAsync(int Identificacion) {
            return base.Channel.ConsultarEstudianteMatriculadoAsync(Identificacion);
        }
        
        public SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3 ModificarEstudianteMatriculado(int Identificacion, SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteDto Datos) {
            return base.Channel.ModificarEstudianteMatriculado(Identificacion, Datos);
        }
        
        public System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfMatriculacionEstudianteRespDto89vZh_Sq3> ModificarEstudianteMatriculadoAsync(int Identificacion, SistemaAcademico.Presentacion.Web.MatriculacionService.MatriculacionEstudianteDto Datos) {
            return base.Channel.ModificarEstudianteMatriculadoAsync(Identificacion, Datos);
        }
        
        public SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfstring EliminarEstudianteMatriculado(int Identificacion) {
            return base.Channel.EliminarEstudianteMatriculado(Identificacion);
        }
        
        public System.Threading.Tasks.Task<SistemaAcademico.Presentacion.Web.MatriculacionService.RespuestaOfstring> EliminarEstudianteMatriculadoAsync(int Identificacion) {
            return base.Channel.EliminarEstudianteMatriculadoAsync(Identificacion);
        }
    }
}
