// <auto-generated />
namespace SistemaAcademico.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlterEstudiante_nombres_apellidos_obligatorios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterEstudiante_nombres_apellidos_obligatorios));
        
        string IMigrationMetadata.Id
        {
            get { return "202003211503526_AlterEstudiante_nombres_apellidos_obligatorios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
